### ISSUE TITLE
use for loop in walk instead of lapply/mapply for better perfomance

### ISSUE THREAD

**Issue by s-fleck** [hrbrmstr/freebase#12]
The whole idea behind walk is that you are not creating the results object. Because of this walk is more efficient than map/lapply in some cases. If you now use lapply/mapply internally to implement walk you are loosing this advantage. This is one of the cases where a for loop is a better choice than lapply/map.

See also original implementation of [purrr::walk ](https://github.com/tidyverse/purrr/blob/master/R/map.R) and [purrr::pwalk](https://github.com/tidyverse/purrr/blob/master/R/map2-pmap.R)

**Comment by hrbrmstr** [comment]
Aye. I totally know the details of the original walkers' implementations and the fact that `for` is faster. This was a super quick initial creation. PRs are welcome if you need the speed faster than I can make time to tweak.

**Comment by s-fleck** [comment]
aye, i'll probably find some time during the week to do a pr for this and maybe a few extra predicate functions
