### ISSUE TITLE
{tbltools}

### ISSUE THREAD

**Issue by mkearney** [hrbrmstr/freebase#15]
I'm not sure if this is useful, but I thought I'd point out that my [{tbltools}](https://github.com/mkearney/tbltools) package has recently turned into a [{dplyr}](https://github.com/tidyverse/dplyr)-lite type of package–similar to [{noplyr}](https://github.com/yonicd/noplyr) only without the [{rlang}](https://github.com/tidyverse/rlang) dependency and a {dplyr_verb}**`_data`** naming convention.

### noplyr:

``` r
> library(magrittr)
> mtcars %>%
+   noplyr::filter(mpg > 11) %>%
+   noplyr::group_by(cyl) %>%
+   noplyr::mutate(n = length(gear)) %>%
+   noplyr::summarize(
+     n = unique(n),
+     mpg = mean(mpg)
+   ) %>%
+   noplyr::arrange(mpg) %>%
+   noplyr::select(cyl, mpg, n)
  cyl      mpg  n
1   4 26.66364 11
2   6 19.74286  7
3   8 15.88333 12
```

### tbltools:

``` r
> library(magrittr)
> mtcars %>%
+   tbltools::filter_data(mpg > 11) %>%
+   tbltools::group_data(cyl) %>%
+   tbltools::mutate_data(n = length(gear)) %>%
+   tbltools::summarise_data(
+     n = unique(n),
+     mpg = mean(mpg)
+   ) %>%
+   tbltools::arrange_data(mpg) %>%
+   tbltools::select_data(cyl, mpg, n)
  cyl      mpg  n
1   4 26.66364 11
2   6 19.74286  7
3   8 15.88333 12
```

**Comment by hrbrmstr** [comment]
oooh! that is highly useful!

**Comment by hrbrmstr** [comment]
zomgosh no name collisions and super fast load time! this will be getting a great deal of use, sir!

**Comment by mkearney** [comment]
Excellent! Will probably make a number of more changes (tests, fixes, and `join`s) in the next few days!

**Comment by yonicd** [comment]
After chats with @mkearney and @krlmlr in Austin

Small update to `noplyr`

Renamed to `bplyr` (`base` + `dplyr`/`tidyr`), with trailing prefix on all functions `b_*`, to resolve NS conflicts with origin pkgs.

https://github.com/yonicd/bplyr
